In [1]:
library(data.table)

In [2]:
mydir = '/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/review_files/'

In [3]:
length(list.files(mydir,"cc.tsv"))
list.files(mydir,"cc.tsv")

[1] 21

 [1] "blueprint_cd14_mono_QTD000021.cc.tsv.gz"
 [2] "blueprint_cd4_QTD000031.cc.tsv.gz"
 [3] "cedar_cd14_mono_QTD000069.cc.tsv.gz"
 [4] "cedar_cd19_b_QTD000073.cc.tsv.gz"
 [5] "cedar_cd4_QTD000067.cc.tsv.gz"
 [6] "cedar_cd8_QTD000066.cc.tsv.gz"
 [7] "kasela_cd4_QTD000371.cc.tsv.gz"
 [8] "kasela_cd8_QTD000372.cc.tsv.gz"
 [9] "schmiedel_b_naive_QTD000474.cc.tsv.gz"
[10] "schmiedel_cd14_mono_QTD000504.cc.tsv.gz"
[11] "schmiedel_cd16_mono_QTD000499.cc.tsv.gz"
[12] "schmiedel_cd4_naive_QTD000479.cc.tsv.gz"
[13] "schmiedel_cd8_naive_QTD000489.cc.tsv.gz"
[14] "schmiedel_nk_QTD000509.cc.tsv.gz"
[15] "schmiedel_tfh_QTD000439.cc.tsv.gz"
[16] "schmiedel_th1_17_QTD000459.cc.tsv.gz"
[17] "schmiedel_th1_QTD000449.cc.tsv.gz"
[18] "schmiedel_th17_QTD000444.cc.tsv.gz"
[19] "schmiedel_th2_QTD000454.cc.tsv.gz"
[20] "schmiedel_treg_mem_QTD000469.cc.tsv.gz"
[21] "schmiedel_treg_naive_QTD000464.cc.tsv.gz"

In [4]:
list.files(mydir,'blueprint')

[1] "big_file_all_blueprint_mono_QTD000021.all.tsv.gz"
[2] "blueprint_1-s2.0-S0092867416314465-mmc3.csv"
[3] "blueprint_1-s2.0-S0092867416314465-mmc3.xlsx"
[4] "blueprint_cd14_mono_QTD000021.cc.tsv.gz"
[5] "blueprint_cd4_QTD000031.cc.tsv.gz"

In [5]:
suppl_tables_dir = '/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/ms_tables/'
df_common_ct = as.data.frame(fread(paste0(suppl_tables_dir,'all_eqtls_fdr_5pct.tsv')))
head(df_common_ct)

  gene            ACAT_p       top_MarkerID                 top_pval
1 ENSG00000020633 5.782049e-04 1:24970252:A:C               1.42751e-05
2 ENSG00000049247 1.234790e-12 1:7913587:T:TTTTTTGTTGTTGTTG 6.48378e-15
3 ENSG00000116288 8.678405e-04 1:8065826:C:CT               8.38885e-06
4 ENSG00000117091 5.320189e-13 1:160705479:G:C              1.97810e-15
5 ENSG00000117394 1.212478e-05 1:42971584:CA:C              2.24877e-07
6 ENSG00000117632 5.598092e-09 1:25972262:A:AT              4.89130e-11
  qvalue       celltype ASDC_is_expressed B_intermediate_is_expressed
1 1.925410e-02 ASDC     TRUE               TRUE
2 2.927374e-10 ASDC     TRUE              FALSE
3 2.624051e-02 ASDC     TRUE               TRUE
4 1.280392e-10 ASDC     TRUE               TRUE
5 7.925513e-04 ASDC     TRUE               TRUE
6 7.800008e-07 ASDC     TRUE               TRUE
  B_memory_is_expressed B_naive_is_expressed ⋯ ILC_is_egene MAIT_is_egene
1  TRUE                  TRUE                ⋯ FALSE         TRUE
2 FALSE                 FALSE                ⋯  TRUE         TRUE
3  TRUE                  TRUE                ⋯ FALSE         TRUE
4  TRUE                  TRUE                ⋯ FALSE         TRUE
5  TRUE                  TRUE                ⋯ FALSE        FALSE
6  TRUE                  TRUE                ⋯ FALSE        FALSE
  NK_is_egene NK_CD56bright_is_egene NK_Proliferating_is_egene pDC_is_egene
1 TRUE        FALSE                  FALSE                     FALSE
2 TRUE         TRUE                   TRUE                     FALSE
3 TRUE         TRUE                   TRUE                      TRUE
4 TRUE         TRUE                   TRUE                      TRUE
5 TRUE        FALSE                  FALSE                     FALSE
6 TRUE        FALSE                  FALSE                      TRUE
  Plasmablast_is_egene Treg_is_egene n_celltypes_expressed n_celltypes_egene
1  TRUE                 TRUE         28                    14
2 FALSE                 TRUE         14                    14
3  TRUE                 TRUE         28                    26
4  TRUE                FALSE         28                    22
5 FALSE                FALSE         27                    10
6 FALSE                 TRUE         28                    15

In [6]:
blueprint_catalogue_file_mono = paste0(mydir,'blueprint_cd14_mono_QTD000021.cc.tsv.gz')
blueprint_df_mono <- read.csv(gzfile(blueprint_catalogue_file_mono), sep="\t")
nrow(blueprint_df_mono)
head(blueprint_df_mono)

[1] 46721320

  molecular_trait_id chromosome position ref alt variant        ma_samples
1 ENSG00000187583    1          14464    A   T   chr1_14464_A_T 41
2 ENSG00000188290    1          14464    A   T   chr1_14464_A_T 41
3 ENSG00000188976    1          14464    A   T   chr1_14464_A_T 41
4 ENSG00000225880    1          14464    A   T   chr1_14464_A_T 41
5 ENSG00000228794    1          14464    A   T   chr1_14464_A_T 41
6 ENSG00000237491    1          14464    A   T   chr1_14464_A_T 41
  maf      pvalue   beta       se       type ac an  r2
1 0.109948 0.151440  0.2556700 0.177460 SNP  42 382 NA
2 0.109948 0.871697 -0.0290366 0.179527 SNP  42 382 NA
3 0.109948 0.778389  0.0477246 0.169326 SNP  42 382 NA
4 0.109948 0.734591 -0.0564960 0.166379 SNP  42 382 NA
5 0.109948 0.302070  0.1687440 0.163032 SNP  42 382 NA
6 0.109948 0.796174  0.0405272 0.156661 SNP  42 382 NA
  molecular_trait_object_id gene_id         median_tpm rsid
1 ENSG00000187583           ENSG00000187583  0.985     rs546169444
2 ENSG00000188290           ENSG00000188290  0.458     rs546169444
3 ENSG00000188976           ENSG00000188976 38.895     rs546169444
4 ENSG00000225880           ENSG00000225880  8.862     rs546169444
5 ENSG00000228794           ENSG00000228794  2.082     rs546169444
6 ENSG00000237491           ENSG00000237491  1.035     rs546169444

In [7]:
length(unique(blueprint_df_mono$molecular_trait_id))
length(unique(blueprint_df_mono[blueprint_df_mono$pvalue < 1e-6,'molecular_trait_id']))

[1] 5720

[1] 5615

In [8]:
# Classical monocytes (CD14+) only
df_mono = df_common_ct[df_common_ct$celltype == 'CD14_Mono',]
tenk10k_monocyte_egenes = unique(df_mono$gene)
length(tenk10k_monocyte_egenes)
length(unique(df_mono[df_mono$top_pval < 1e-6,]$gene))

[1] 9026

[1] 5468

In [15]:
blueprint_egenes = unique(blueprint_df_mono[blueprint_df_mono$pvalue < 1e-6,'molecular_trait_id'])
length(blueprint_egenes)
tenk10k_egenes = unique(df_mono[df_mono$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(blueprint_egenes[blueprint_egenes %in% tenk10k_egenes])
length(blueprint_egenes[blueprint_egenes %in% tenk10k_egenes])/length(blueprint_egenes)

[1] 5615

[1] 5468

[1] 3485

[1] 0.6206589

In [16]:
blueprint_catalogue_file_cd4 = paste0(mydir,'blueprint_cd4_QTD000031.cc.tsv.gz')
blueprint_df_cd4 <- read.csv(gzfile(blueprint_catalogue_file_cd4), sep="\t")
nrow(blueprint_df_cd4)
head(blueprint_df_cd4)

[1] 42422623

  molecular_trait_id chromosome position ref alt variant        ma_samples
1 ENSG00000187608    1          14464    A   T   chr1_14464_A_T 39
2 ENSG00000188290    1          14464    A   T   chr1_14464_A_T 39
3 ENSG00000225880    1          14464    A   T   chr1_14464_A_T 39
4 ENSG00000228794    1          14464    A   T   chr1_14464_A_T 39
5 ENSG00000237491    1          14464    A   T   chr1_14464_A_T 39
6 ENSG00000187608    1          15447    A   G   chr1_15447_A_G  8
  maf       pvalue    beta      se       type ac an  r2
1 0.1197600 0.0550782 0.2987070 0.154519 SNP  40 334 NA
2 0.1197600 0.5366600 0.1146650 0.185158 SNP  40 334 NA
3 0.1197600 0.8407900 0.0356372 0.177099 SNP  40 334 NA
4 0.1197600 0.3649420 0.1440090 0.158476 SNP  40 334 NA
5 0.1197600 0.4311790 0.1153380 0.146131 SNP  40 334 NA
6 0.0239521 0.8834920 0.0617455 0.420637 SNP   6 334 NA
  molecular_trait_object_id gene_id         median_tpm rsid
1 ENSG00000187608           ENSG00000187608 69.840     rs546169444
2 ENSG00000188290           ENSG00000188290  0.987     rs546169444
3 ENSG00000225880           ENSG00000225880  9.432     rs546169444
4 ENSG00000228794           ENSG00000228794  9.607     rs546169444
5 ENSG00000237491           ENSG00000237491  0.612     rs546169444
6 ENSG00000187608           ENSG00000187608 69.840     rs201635489

In [17]:
length(unique(blueprint_df_cd4$molecular_trait_id))
length(unique(blueprint_df_cd4[blueprint_df_cd4$pvalue < 1e-6,'molecular_trait_id']))

[1] 5114

[1] 5035

In [18]:
# All CD4
all_celltypes = unique(df_common_ct$celltype)
cd4_celltypes = all_celltypes[grep('CD4',all_celltypes)]
cd4_celltypes = c(cd4_celltypes,'Treg')
cd4_celltypes

[1] "CD4_CTL"           "CD4_Naive"         "CD4_Proliferating"
[4] "CD4_TCM"           "CD4_TEM"           "Treg"

In [19]:
df_cd4 = df_common_ct[df_common_ct$celltype %in% cd4_celltypes,]
tenk10k_cd4_egenes = unique(df_cd4$gene)
length(tenk10k_cd4_egenes)
length(unique(df_cd4[df_cd4$top_pval < 1e-6,]$gene))

[1] 13284

[1] 9297

In [20]:
blueprint_egenes = unique(blueprint_df_cd4[blueprint_df_cd4$pvalue < 1e-6,'molecular_trait_id'])
length(blueprint_egenes)
tenk10k_egenes = unique(df_cd4[df_cd4$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(blueprint_egenes[blueprint_egenes %in% tenk10k_egenes])
length(blueprint_egenes[blueprint_egenes %in% tenk10k_egenes])/length(blueprint_egenes)

[1] 5035

[1] 9297

[1] 3771

[1] 0.7489573

In [29]:
blueprint_df <- fread(paste0(mydir,'blueprint_1-s2.0-S0092867416314465-mmc3.csv'))
colnames(blueprint_df) = as.character(blueprint_df[4,])
colnames(blueprint_df)[4:13] = paste0('Monocyte_',colnames(blueprint_df)[4:13])
colnames(blueprint_df)[14:23] = paste0('Neutrophil_',colnames(blueprint_df)[14:23])
colnames(blueprint_df)[24:30] = paste0('CD4_',colnames(blueprint_df)[24:30])
blueprint_df <- blueprint_df[-c(1:4),]
nrow(blueprint_df)
head(blueprint_df,2)

[1] 23445

  ENSEMBL ID        Gene type      HGNC gene Monocyte_VD_Meth
1 ENSG00000000419.8 protein_coding DPM1      0
2 ENSG00000000457.8 protein_coding SCYL3     0
  Monocyte_VD_H3K4me1 Monocyte_VD_H3K27ac Monocyte_VD_H3K4me1.H3K27ac
1 0                   0                   0
2 0                   0                   0
  Monocyte_VD_Geno Monocyte_eQTL Monocyte_ASE ⋯ CD4_eQTL CD4_ASE CD4_CHT
1 0                0             0            ⋯ 0        0       1
2 0                0             1            ⋯ 1        1       1
  CD4_ISO CD4_PSI Symbol (Entrez)
1 NA      NA      DPM1
2 1       0       SCYL3
  Gene Name (Entrez)
1 dolichyl-phosphate mannosyltransferase polypeptide 1, catalytic subunit
2 SCY1 like pseudokinase 3
  Location  Type(s) Gene ID mismatches
1 Cytoplasm enzyme  TRUE
2 Cytoplasm kinase  TRUE

In [30]:
monocyte_df = blueprint_df[blueprint_df$Monocyte_eQTL == 1,]
nrow(monocyte_df)
head(monocyte_df)

[1] 6513

  ENSEMBL ID         Gene type      HGNC gene Monocyte_VD_Meth
1 ENSG00000000460.11 protein_coding C1orf112  0
2 ENSG00000001036.8  protein_coding FUCA2     0
3 ENSG00000001084.6  protein_coding GCLC      0
4 ENSG00000001460.13 protein_coding STPG1     0
5 ENSG00000001461.11 protein_coding NIPAL3    0
6 ENSG00000001561.5  protein_coding ENPP4     0
  Monocyte_VD_H3K4me1 Monocyte_VD_H3K27ac Monocyte_VD_H3K4me1.H3K27ac
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 1                   0                   1
  Monocyte_VD_Geno Monocyte_eQTL Monocyte_ASE ⋯ CD4_eQTL CD4_ASE CD4_CHT
1 1                1             1            ⋯ 1        1       1
2 1                1             1            ⋯ 0        1       1
3 0                1             1            ⋯ 0        1       1
4 1                1             1            ⋯ 1        1       1
5 0                1             1            ⋯ 1        1       1
6 1                1             1            ⋯ 1        1       1
  CD4_ISO CD4_PSI Symbol (Entrez)
1 NA      NA      C1orf112
2 NA      NA      FUCA2
3 NA      NA      GCLC
4 NA      NA      STPG1
5 1       0       NIPAL3
6 NA      NA      ENPP4
  Gene Name (Entrez)
1 chromosome 1 open reading frame 112
2 fucosidase, alpha-L- 2, plasma
3 glutamate-cysteine ligase catalytic subunit
4 sperm tail PG-rich repeat containing 1
5 NIPA like domain containing 3
6 ectonucleotide pyrophosphatase/phosphodiesterase 4 (putative)
  Location            Type(s) Gene ID mismatches
1 Other               other   TRUE
2 Extracellular Space enzyme  TRUE
3 Cytoplasm           enzyme  TRUE
4 Other               other   TRUE
5 Other               other   TRUE
6 Cytoplasm           enzyme  TRUE

In [35]:
monocytes_egenes = gsub('\\..*','',unique(monocyte_df[['ENSEMBL ID']]))
length(monocytes_egenes)
head(monocytes_egenes)

[1] 6513

[1] "ENSG00000000460" "ENSG00000001036" "ENSG00000001084" "ENSG00000001460"
[5] "ENSG00000001461" "ENSG00000001561"

  gene            ACAT_p       top_MarkerID                 top_pval
1 ENSG00000020633 5.782049e-04 1:24970252:A:C               1.42751e-05
2 ENSG00000049247 1.234790e-12 1:7913587:T:TTTTTTGTTGTTGTTG 6.48378e-15
3 ENSG00000116288 8.678405e-04 1:8065826:C:CT               8.38885e-06
4 ENSG00000117091 5.320189e-13 1:160705479:G:C              1.97810e-15
5 ENSG00000117394 1.212478e-05 1:42971584:CA:C              2.24877e-07
6 ENSG00000117632 5.598092e-09 1:25972262:A:AT              4.89130e-11
  qvalue       celltype ASDC_is_expressed B_intermediate_is_expressed
1 1.925410e-02 ASDC     TRUE               TRUE
2 2.927374e-10 ASDC     TRUE              FALSE
3 2.624051e-02 ASDC     TRUE               TRUE
4 1.280392e-10 ASDC     TRUE               TRUE
5 7.925513e-04 ASDC     TRUE               TRUE
6 7.800008e-07 ASDC     TRUE               TRUE
  B_memory_is_expressed B_naive_is_expressed ⋯ ILC_is_egene MAIT_is_egene
1  TRUE                  TRUE                ⋯ FALSE         TRUE
2 FALSE                 FALSE                ⋯  TRUE         TRUE
3  TRUE                  TRUE                ⋯ FALSE         TRUE
4  TRUE                  TRUE                ⋯ FALSE         TRUE
5  TRUE                  TRUE                ⋯ FALSE        FALSE
6  TRUE                  TRUE                ⋯ FALSE        FALSE
  NK_is_egene NK_CD56bright_is_egene NK_Proliferating_is_egene pDC_is_egene
1 TRUE        FALSE                  FALSE                     FALSE
2 TRUE         TRUE                   TRUE                     FALSE
3 TRUE         TRUE                   TRUE                      TRUE
4 TRUE         TRUE                   TRUE                      TRUE
5 TRUE        FALSE                  FALSE                     FALSE
6 TRUE        FALSE                  FALSE                      TRUE
  Plasmablast_is_egene Treg_is_egene n_celltypes_expressed n_celltypes_egene
1  TRUE                 TRUE         28                    14
2 FALSE                 TRUE         14                    14
3  TRUE                 TRUE         28                    26
4  TRUE                FALSE         28                    22
5 FALSE                FALSE         27                    10
6 FALSE                 TRUE         28                    15

In [38]:
# Classical monocytes (CD14+) only
df_mono = df_common_ct[df_common_ct$celltype == 'CD14_Mono',]
tenk10k_monocyte_egenes = unique(df_mono$gene)
length(tenk10k_monocyte_egenes)

[1] 9026

In [39]:
tenk10k_egenes_unique = tenk10k_monocyte_egenes[!(tenk10k_monocyte_egenes %in% monocytes_egenes)]
length(tenk10k_egenes_unique)

[1] 4451

In [40]:
blueprint_mono_egenes_unique = monocytes_egenes[!(monocytes_egenes %in% tenk10k_monocyte_egenes)]
length(blueprint_mono_egenes_unique)

[1] 1938