In [2]:
library(data.table)

In [3]:
mydir = '/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/review_files/'

In [4]:
length(list.files(mydir,"cc.tsv"))
list.files(mydir,"cc.tsv")

[1] 21

 [1] "blueprint_cd14_mono_QTD000021.cc.tsv.gz"
 [2] "blueprint_cd4_QTD000031.cc.tsv.gz"
 [3] "cedar_cd14_mono_QTD000069.cc.tsv.gz"
 [4] "cedar_cd19_b_QTD000073.cc.tsv.gz"
 [5] "cedar_cd4_QTD000067.cc.tsv.gz"
 [6] "cedar_cd8_QTD000066.cc.tsv.gz"
 [7] "kasela_cd4_QTD000371.cc.tsv.gz"
 [8] "kasela_cd8_QTD000372.cc.tsv.gz"
 [9] "schmiedel_b_naive_QTD000474.cc.tsv.gz"
[10] "schmiedel_cd14_mono_QTD000504.cc.tsv.gz"
[11] "schmiedel_cd16_mono_QTD000499.cc.tsv.gz"
[12] "schmiedel_cd4_naive_QTD000479.cc.tsv.gz"
[13] "schmiedel_cd8_naive_QTD000489.cc.tsv.gz"
[14] "schmiedel_nk_QTD000509.cc.tsv.gz"
[15] "schmiedel_tfh_QTD000439.cc.tsv.gz"
[16] "schmiedel_th1_17_QTD000459.cc.tsv.gz"
[17] "schmiedel_th1_QTD000449.cc.tsv.gz"
[18] "schmiedel_th17_QTD000444.cc.tsv.gz"
[19] "schmiedel_th2_QTD000454.cc.tsv.gz"
[20] "schmiedel_treg_mem_QTD000469.cc.tsv.gz"
[21] "schmiedel_treg_naive_QTD000464.cc.tsv.gz"

In [5]:
list.files(mydir,"cedar")

[1] "cedar_41467_2018_4365_MOESM3_ESM.xlsx"
[2] "cedar_cd14_mono_QTD000069.cc.tsv.gz"
[3] "cedar_cd19_b_QTD000073.cc.tsv.gz"
[4] "cedar_cd4_QTD000067.cc.tsv.gz"
[5] "cedar_cd8_QTD000066.cc.tsv.gz"

In [6]:
suppl_tables_dir = '/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/ms_tables/'
df_common_ct = as.data.frame(fread(paste0(suppl_tables_dir,'all_eqtls_fdr_5pct.tsv')))
head(df_common_ct,2)

  gene            ACAT_p       top_MarkerID                 top_pval
1 ENSG00000020633 5.782049e-04 1:24970252:A:C               1.42751e-05
2 ENSG00000049247 1.234790e-12 1:7913587:T:TTTTTTGTTGTTGTTG 6.48378e-15
  qvalue       celltype ASDC_is_expressed B_intermediate_is_expressed
1 1.925410e-02 ASDC     TRUE               TRUE
2 2.927374e-10 ASDC     TRUE              FALSE
  B_memory_is_expressed B_naive_is_expressed ⋯ ILC_is_egene MAIT_is_egene
1  TRUE                  TRUE                ⋯ FALSE        TRUE
2 FALSE                 FALSE                ⋯  TRUE        TRUE
  NK_is_egene NK_CD56bright_is_egene NK_Proliferating_is_egene pDC_is_egene
1 TRUE        FALSE                  FALSE                     FALSE
2 TRUE         TRUE                   TRUE                     FALSE
  Plasmablast_is_egene Treg_is_egene n_celltypes_expressed n_celltypes_egene
1  TRUE                TRUE          28                    14
2 FALSE                TRUE          14                    14

In [7]:
# All CD4
all_celltypes = unique(df_common_ct$celltype)
cd4_celltypes = all_celltypes[grep('CD4',all_celltypes)]
cd4_celltypes = c(cd4_celltypes,'Treg')
cd4_celltypes

[1] "CD4_CTL"           "CD4_Naive"         "CD4_Proliferating"
[4] "CD4_TCM"           "CD4_TEM"           "Treg"

In [8]:
df_cd4 = df_common_ct[df_common_ct$celltype %in% cd4_celltypes,]
tenk10k_cd4_egenes = unique(df_cd4$gene)
length(tenk10k_cd4_egenes)
length(unique(df_cd4[df_cd4$top_pval < 1e-6,]$gene))

[1] 13284

[1] 9297

In [9]:
cedar_catalogue_file_cd4 = paste0(mydir,'cedar_cd4_QTD000067.cc.tsv.gz')
cedar_df_cd4 <- read.csv(gzfile(cedar_catalogue_file_cd4), sep="\t")
nrow(cedar_df_cd4)
head(cedar_df_cd4)

length(unique(cedar_df_cd4$molecular_trait_id))
length(unique(cedar_df_cd4[cedar_df_cd4$pvalue < 1e-6,'molecular_trait_id']))

[1] 20810072

  molecular_trait_id chromosome position ref alt variant         ma_samples maf
1 ILMN_1696065       1          758351   A   G   chr1_758351_A_G 58         0.1
2 ILMN_1739749       1          758351   A   G   chr1_758351_A_G 58         0.1
3 ILMN_2054019       1          758351   A   G   chr1_758351_A_G 58         0.1
4 ILMN_2234310       1          758351   A   G   chr1_758351_A_G 58         0.1
5 ILMN_3228585       1          758351   A   G   chr1_758351_A_G 58         0.1
6 ILMN_3300663       1          758351   A   G   chr1_758351_A_G 58         0.1
  pvalue   beta        se       type ac an  r2      molecular_trait_object_id
1 0.187972 -0.20638300 0.156365 SNP  47 580 0.40366 ENSG00000078808
2 0.624315  0.10270100 0.209468 SNP  47 580 0.40366 ENSG00000176022
3 0.935961 -0.01323670 0.164592 SNP  47 580 0.40366 ENSG00000187608
4 0.290911 -0.21258500 0.200900 SNP  47 580 0.40366 ENSG00000224051
5 0.768092  0.04202660 0.142384 SNP  47 580 0.40366 ENSG00000189339
6 0.962894  0.00567494 0.121873 SNP  47 580 0.40366 ENSG00000189339
  gene_id         median_tpm rsid
1 ENSG00000078808 NA         rs12238997
2 ENSG00000176022 NA         rs12238997
3 ENSG00000187608 NA         rs12238997
4 ENSG00000224051 NA         rs12238997
5 ENSG00000189339 NA         rs12238997
6 ENSG00000189339 NA         rs12238997

[1] 2483

[1] 2454

In [27]:
cedar_egenes = unique(cedar_df_cd4[cedar_df_cd4$pvalue < 1e-6,'gene_id'])
length(cedar_egenes)
tenk10k_egenes = unique(df_cd4[df_cd4$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(cedar_egenes[cedar_egenes %in% tenk10k_egenes])
length(cedar_egenes[cedar_egenes %in% tenk10k_egenes])/length(cedar_egenes)

[1] 2079

[1] 9297

[1] 1668

[1] 0.8023088

In [11]:
# All CD8
cd8_celltypes = all_celltypes[grep('CD8',all_celltypes)]
cd8_celltypes

[1] "CD8_Naive"         "CD8_Proliferating" "CD8_TCM"
[4] "CD8_TEM"

In [12]:
df_cd8 = df_common_ct[df_common_ct$celltype %in% cd8_celltypes,]
tenk10k_cd8_egenes = unique(df_cd8$gene)
length(tenk10k_cd8_egenes)
length(unique(df_cd8[df_cd8$top_pval < 1e-6,]$gene))

[1] 12396

[1] 8238

In [13]:
cedar_catalogue_file_cd8 = paste0(mydir,'cedar_cd8_QTD000066.cc.tsv.gz')
cedar_df_cd8 <- read.csv(gzfile(cedar_catalogue_file_cd8), sep="\t")
nrow(cedar_df_cd8)
head(cedar_df_cd8,2)

length(unique(cedar_df_cd8$molecular_trait_id))
length(unique(cedar_df_cd8[cedar_df_cd8$pvalue < 1e-6,'molecular_trait_id']))

[1] 16400435

  molecular_trait_id chromosome position ref alt variant         ma_samples
1 ILMN_1696065       1          758351   A   G   chr1_758351_A_G 52
2 ILMN_1739749       1          758351   A   G   chr1_758351_A_G 52
  maf       pvalue    beta       se       type ac an  r2
1 0.0938628 0.7615200 -0.0397634 0.130886 SNP  41 554 0.40366
2 0.0938628 0.0280253  0.4577950 0.207221 SNP  41 554 0.40366
  molecular_trait_object_id gene_id         median_tpm rsid
1 ENSG00000078808           ENSG00000078808 NA         rs12238997
2 ENSG00000176022           ENSG00000176022 NA         rs12238997

[1] 1972

[1] 1951

In [28]:
cedar_egenes = unique(cedar_df_cd8[cedar_df_cd8$pvalue < 1e-6,'gene_id'])
length(cedar_egenes)
tenk10k_egenes = unique(df_cd8[df_cd8$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(cedar_egenes[cedar_egenes %in% tenk10k_egenes])
length(cedar_egenes[cedar_egenes %in% tenk10k_egenes])/length(cedar_egenes)

[1] 1659

[1] 8238

[1] 1261

[1] 0.7600964

In [23]:
# Classical monocytes (CD14+) only
df_mono = df_common_ct[df_common_ct$celltype == 'CD14_Mono',]
tenk10k_monocyte_egenes = unique(df_mono$gene)
length(tenk10k_monocyte_egenes)
length(unique(df_mono[df_mono$top_pval < 1e-6,]$gene))

[1] 9026

[1] 5468

In [24]:
cedar_catalogue_file_mono = paste0(mydir,'cedar_cd14_mono_QTD000069.cc.tsv.gz')
cedar_df_mono <- read.csv(gzfile(cedar_catalogue_file_mono), sep="\t")
nrow(cedar_df_mono)
head(cedar_df_mono,2)

length(unique(cedar_df_mono$molecular_trait_id))
length(unique(cedar_df_mono[cedar_df_mono$pvalue < 1e-6,'molecular_trait_id']))

[1] 19553661

  molecular_trait_id chromosome position ref alt variant         ma_samples
1 ILMN_1653466       1          758351   A   G   chr1_758351_A_G 54
2 ILMN_1664956       1          758351   A   G   chr1_758351_A_G 54
  maf       pvalue   beta      se       type ac an  r2
1 0.0944056 0.148332 -0.301526 0.208009 SNP  43 572 0.40366
2 0.0944056 0.877822 -0.033635 0.218586 SNP  43 572 0.40366
  molecular_trait_object_id gene_id         median_tpm rsid
1 ENSG00000188290           ENSG00000188290 NA         rs12238997
2 ENSG00000160075           ENSG00000160075 NA         rs12238997

[1] 2342

[1] 2315

In [26]:
cedar_egenes = unique(cedar_df_mono[cedar_df_mono$pvalue < 1e-6,'gene_id'])
length(cedar_egenes)
tenk10k_egenes = unique(df_mono[df_mono$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(cedar_egenes[cedar_egenes %in% tenk10k_egenes])
length(cedar_egenes[cedar_egenes %in% tenk10k_egenes])/length(cedar_egenes)

[1] 1965

[1] 5468

[1] 1337

[1] 0.6804071

In [18]:
# All B cells
b_celltypes = all_celltypes[grep('B',all_celltypes)]
b_celltypes

[1] "B_intermediate" "B_memory"       "B_naive"

In [19]:
df_b = df_common_ct[df_common_ct$celltype %in% b_celltypes,]
tenk10k_b_egenes = unique(df_b$gene)
length(tenk10k_b_egenes)
length(unique(df_b[df_b$top_pval < 1e-6,]$gene))

[1] 11058

[1] 6833

In [20]:
cedar_catalogue_file_b = paste0(mydir,'cedar_cd19_b_QTD000073.cc.tsv.gz')
cedar_df_b <- read.csv(gzfile(cedar_catalogue_file_b), sep="\t")
nrow(cedar_df_b)
head(cedar_df_b)

[1] 523623

  molecular_trait_id chromosome position ref alt  variant            ma_samples
1 ILMN_1739749       1          758351   A   G    chr1_758351_A_G    51
2 ILMN_2054019       1          758351   A   G    chr1_758351_A_G    51
3 ILMN_1739749       1          758443   G   C    chr1_758443_G_C    55
4 ILMN_2054019       1          758443   G   C    chr1_758443_G_C    55
5 ILMN_1739749       1          791100   G   GGGA chr1_791100_G_GGGA 62
6 ILMN_2054019       1          791100   G   GGGA chr1_791100_G_GGGA 62
  maf       pvalue   beta        se       type  ac an  r2
1 0.0973282 0.937990 -0.01819940 0.233698 SNP   41 524 0.40366
2 0.0973282 0.428973  0.14079600 0.177716 SNP   41 524 0.40366
3 0.1049620 0.926799 -0.02099420 0.228282 SNP   51 524 0.41763
4 0.1049620 0.450422  0.13124100 0.173619 SNP   51 524 0.41763
5 0.1183210 0.985543 -0.00372377 0.205296 INDEL 60 524 0.49295
6 0.1183210 0.654307  0.07005230 0.156251 INDEL 60 524 0.49295
  molecular_trait_object_id gene_id         median_tpm rsid
1 ENSG00000176022           ENSG00000176022 NA         rs12238997
2 ENSG00000187608           ENSG00000187608 NA         rs12238997
3 ENSG00000176022           ENSG00000176022 NA         rs61769351
4 ENSG00000187608           ENSG00000187608 NA         rs61769351
5 ENSG00000176022           ENSG00000176022 NA         rs1323158546
6 ENSG00000187608           ENSG00000187608 NA         rs1323158546

In [21]:
length(unique(cedar_df_b$molecular_trait_id))
length(unique(cedar_df_b[cedar_df_b$pvalue < 1e-6,'molecular_trait_id']))

[1] 73

[1] 72

In [22]:
cedar_egenes = unique(cedar_df_b[cedar_df_b$pvalue < 1e-6,'molecular_trait_id'])
length(cedar_egenes)
tenk10k_egenes = unique(df_b[df_b$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(cedar_egenes[cedar_egenes %in% tenk10k_egenes])
length(cedar_egenes[cedar_egenes %in% tenk10k_egenes])/length(cedar_egenes)

[1] 72

[1] 6833

[1] 0

[1] 0