In [1]:
library(data.table)

In [2]:
mydir = '/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/review_files/'

In [3]:
length(list.files(mydir,"cc.tsv"))
# list.files(mydir,"cc.tsv")

[1] 21

In [4]:
list.files(mydir,'kasela')

[1] "kasela_cd4_QTD000371.cc.tsv.gz" "kasela_cd8_QTD000372.cc.tsv.gz"
[3] "kasela_pgen.1006643.s010.xlsx"

In [9]:
suppl_tables_dir = '/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/ms_tables/'
df_common_ct = as.data.frame(fread(paste0(suppl_tables_dir,'all_eqtls_fdr_5pct.tsv')))
head(df_common_ct,2)

  gene            ACAT_p       top_MarkerID                 top_pval
1 ENSG00000020633 5.782049e-04 1:24970252:A:C               1.42751e-05
2 ENSG00000049247 1.234790e-12 1:7913587:T:TTTTTTGTTGTTGTTG 6.48378e-15
  qvalue       celltype ASDC_is_expressed B_intermediate_is_expressed
1 1.925410e-02 ASDC     TRUE               TRUE
2 2.927374e-10 ASDC     TRUE              FALSE
  B_memory_is_expressed B_naive_is_expressed ⋯ ILC_is_egene MAIT_is_egene
1  TRUE                  TRUE                ⋯ FALSE        TRUE
2 FALSE                 FALSE                ⋯  TRUE        TRUE
  NK_is_egene NK_CD56bright_is_egene NK_Proliferating_is_egene pDC_is_egene
1 TRUE        FALSE                  FALSE                     FALSE
2 TRUE         TRUE                   TRUE                     FALSE
  Plasmablast_is_egene Treg_is_egene n_celltypes_expressed n_celltypes_egene
1  TRUE                TRUE          28                    14
2 FALSE                TRUE          14                    14

In [6]:
# All CD4
all_celltypes = unique(df_common_ct$celltype)
cd4_celltypes = all_celltypes[grep('CD4',all_celltypes)]
cd4_celltypes = c(cd4_celltypes,'Treg')
cd4_celltypes

[1] "CD4_CTL"           "CD4_Naive"         "CD4_Proliferating"
[4] "CD4_TCM"           "CD4_TEM"           "Treg"

In [7]:
df_cd4 = df_common_ct[df_common_ct$celltype %in% cd4_celltypes,]
tenk10k_cd4_egenes = unique(df_cd4$gene)
length(tenk10k_cd4_egenes)

[1] 13284

In [8]:
length(unique(df_cd4[df_cd4$top_pval < 1e-6,]$gene))

[1] 9297

In [10]:
kasela_catalogue_file_cd4 = paste0(mydir,'kasela_cd4_QTD000371.cc.tsv.gz')
kasela_df_cd4 <- read.csv(gzfile(kasela_catalogue_file_cd4), sep="\t")
nrow(kasela_df_cd4)
head(kasela_df_cd4)
length(unique(kasela_df_cd4$molecular_trait_id))
length(unique(kasela_df_cd4[kasela_df_cd4$pvalue < 1e-6,'molecular_trait_id']))

[1] 16609429

  molecular_trait_id chromosome position ref alt variant         ma_samples
1 ILMN_1653466       1          619038   G   A   chr1_619038_G_A 6
2 ILMN_2054019       1          619038   G   A   chr1_619038_G_A 6
3 ILMN_3237598       1          619038   G   A   chr1_619038_G_A 6
4 ILMN_1653466       1          740366   G   C   chr1_740366_G_C 6
5 ILMN_2054019       1          740366   G   C   chr1_740366_G_C 6
6 ILMN_3237598       1          740366   G   C   chr1_740366_G_C 6
  maf       pvalue   beta        se       type ac an  r2
1 0.0107143 0.922554 -0.05813280 0.597402 SNP  6  560 0.46780
2 0.0107143 0.986780  0.00827656 0.499047 SNP  6  560 0.46780
3 0.0107143 0.782843  0.18472800 0.669557 SNP  6  560 0.46780
4 0.0107143 0.995677 -0.00318385 0.587065 SNP  6  560 0.45387
5 0.0107143 0.916590  0.05140780 0.490393 SNP  6  560 0.45387
6 0.0107143 0.508670  0.43514500 0.657511 SNP  6  560 0.45387
  molecular_trait_object_id gene_id         median_tpm rsid
1 ENSG00000188290           ENSG00000188290 NA         rs1421262374
2 ENSG00000187608           ENSG00000187608 NA         rs1421262374
3 ENSG00000225880           ENSG00000225880 NA         rs1421262374
4 ENSG00000188290           ENSG00000188290 NA         rs1465398753
5 ENSG00000187608           ENSG00000187608 NA         rs1465398753
6 ENSG00000225880           ENSG00000225880 NA         rs1465398753

[1] 1986

[1] 1971

In [11]:
kasela_egenes = unique(kasela_df_cd4[kasela_df_cd4$pvalue < 1e-6,'gene_id'])
length(kasela_egenes)
tenk10k_egenes = unique(df_cd4[df_cd4$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(kasela_egenes[kasela_egenes %in% tenk10k_egenes])
length(kasela_egenes[kasela_egenes %in% tenk10k_egenes])/length(kasela_egenes)

[1] 1669

[1] 9297

[1] 1349

[1] 0.8082684

In [12]:
# All CD8
cd8_celltypes = all_celltypes[grep('CD8',all_celltypes)]
cd8_celltypes

[1] "CD8_Naive"         "CD8_Proliferating" "CD8_TCM"
[4] "CD8_TEM"

In [13]:
df_cd8 = df_common_ct[df_common_ct$celltype %in% cd8_celltypes,]
tenk10k_cd8_egenes = unique(df_cd8$gene)
length(tenk10k_cd8_egenes)
length(unique(df_cd8[df_cd8$top_pval < 1e-6,]$gene))

[1] 12396

[1] 8238

In [14]:
kasela_catalogue_file_cd8 = paste0(mydir,'kasela_cd8_QTD000372.cc.tsv.gz')
kasela_df_cd8 <- read.csv(gzfile(kasela_catalogue_file_cd8), sep="\t")
nrow(kasela_df_cd8)
head(kasela_df_cd8)

[1] 10108473

  molecular_trait_id chromosome position ref    alt variant
1 ILMN_3237598       1          619038   G      A   chr1_619038_G_A
2 ILMN_3237598       1          740366   G      C   chr1_740366_G_C
3 ILMN_3237598       1          758351   A      G   chr1_758351_A_G
4 ILMN_3237598       1          758443   G      C   chr1_758443_G_C
5 ILMN_3237598       1          772142   G      C   chr1_772142_G_C
6 ILMN_3237598       1          789568   TATGGA T   chr1_789568_TATGGA_T
  ma_samples maf       pvalue      beta      se       type  ac  an  r2
1   6        0.0111524 4.67341e-01  0.485343 0.666765 SNP     6 538 0.46780
2   6        0.0111524 4.75793e-01  0.474457 0.664371 SNP     6 538 0.45387
3  63        0.1171000 7.67525e-07  0.971966 0.191711 SNP    52 538 0.42434
4  74        0.1375460 5.10285e-07  0.958640 0.185963 SNP    67 538 0.44101
5  42        0.0780669 1.12991e-06  1.023280 0.205132 SNP    39 538 0.40326
6 120        0.2397770 2.97982e-07 -0.709231 0.134694 INDEL 414 538 0.40426
  molecular_trait_object_id gene_id         median_tpm rsid
1 ENSG00000225880           ENSG00000225880 NA         rs1421262374
2 ENSG00000225880           ENSG00000225880 NA         rs1465398753
3 ENSG00000225880           ENSG00000225880 NA         rs12238997
4 ENSG00000225880           ENSG00000225880 NA         rs61769351
5 ENSG00000225880           ENSG00000225880 NA         rs371890604
6 ENSG00000225880           ENSG00000225880 NA         rs200087344

In [15]:
length(unique(kasela_df_cd8$molecular_trait_id))

[1] 1213

In [16]:
length(unique(kasela_df_cd8[kasela_df_cd8$pvalue < 1e-6,'molecular_trait_id']))

[1] 1201

In [17]:
kasela_egenes = unique(kasela_df_cd8[kasela_df_cd8$pvalue < 1e-6,'gene_id'])
length(kasela_egenes)
tenk10k_egenes = unique(df_cd8[df_cd8$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(kasela_egenes[kasela_egenes %in% tenk10k_egenes])
length(kasela_egenes[kasela_egenes %in% tenk10k_egenes])/length(kasela_egenes)

[1] 1027

[1] 8238

[1] 811

[1] 0.7896787